#!/usr/bin/env ruby

Dir.chdir File.dirname(__FILE__)

def run_job(job)
  system "./piglobot.rb", job
end

%w( LANN AàC suivi_portail_informatique change ).each do |job|
  run_job job
end

if Time.now.wday == 0
  run_job "inactive_admins"
end
