#!/usr/bin/env ruby

Dir.chdir File.dirname(__FILE__)

system "./spec -t 30 wiki_spec_live.rb" or raise "Live spec failed"

def run_job(job)
  system "./piglobot.rb", job
end

%w( LANN AàC suivi_portail_informatique change ).each do |job|
  run_job job
end

if Time.now.wday == 0
  run_job "inactive_admins"
end
