#!/usr/bin/env ruby

Dir.chdir File.dirname(__FILE__)

unless system "./spec -t 90 wiki_spec_live.rb"
  system "ruby", "-rpiglobot", "-e", "Piglobot.new.notice 'Les tests de compatibilité avec la version actuelle de mediawiki ont échoué. Tous les travaux en cours sont suspendus.'"
  raise "Live spec failed"
end

def run_job(job)
  system "./piglobot.rb", job
end

%w( LANN AàC suivi_portail_informatique change ).each do |job|
  run_job job
end

if Time.now.wday == 0
  run_job "inactive_admins"
end
