#!/usr/bin/env ruby

target = ARGV.shift
raise "usage: #$0 <target>" unless target

urls = {
  "samples/test_links_lann.html" =>
    "http://fr.wikipedia.org/wiki/Special:Pages_li%C3%A9es/Mod%C3%A8le:Archive_LANN",
  "samples/admin_list_1.html" =>
    "http://fr.wikipedia.org/w/index.php?title=Special:Liste_des_utilisateurs&group=sysop&limit=50",
  "samples/admin_list_2.html" =>
    "http://fr.wikipedia.org/w/index.php?title=Special:Listusers&group=sysop&limit=50&offset=GL",
  "samples/edit.html" =>
    "http://fr.wikipedia.org/w/index.php?title=Utilisateur:Piglobot/Page_de_test&action=edit",
  "samples/empty_page.html" =>
    "http://fr.wikipedia.org/w/index.php?title=Utilisateur:Piglobot/Page_de_test_inexistante&action=edit",
  "samples/lann_category.html" =>
    "http://fr.wikipedia.org/w/index.php?title=Cat%C3%A9gorie:Wikip%C3%A9dia:Archives_Articles_non_neutres&from=Wikip%C3%A9dia%3AListe+des+articles+non+neutres%2FBernard+Lugan",
  "samples/contributions.html" =>
    "http://fr.wikipedia.org/w/index.php?limit=3&title=Sp%C3%A9cial%3AContributions&contribs=user&target=Piglobot&namespace=&year=2008&month=7",
  "samples/contributions_2.html" =>
    "http://fr.wikipedia.org/w/index.php?title=Sp%C3%A9cial:Contributions&offset=20071203195253&contribs=user&target=Piglop&limit=1",
  "samples/contributions_3.html" =>
    "http://fr.wikipedia.org/w/index.php?title=Sp%C3%A9cial:Contributions&dir=prev&offset=20071204075134&limit=1&contribs=user&target=69.70.212.195",
  "samples/contributions_4.html" =>
    "http://fr.wikipedia.org/w/index.php?title=Sp%C3%A9cial:Contributions&offset=20071113143800&limit=1&contribs=user&target=129.194.8.73",
  "samples/history.html" => "http://fr.wikipedia.org/w/index.php?title=Wikip%C3%A9dia&dir=prev&offset=20071023064530&limit=4&action=history",
  "samples/category.html" =>
    "http://fr.wikipedia.org/wiki/Cat%C3%A9gorie:Wikip%C3%A9dia:Archives_Articles_non_neutres",
  "samples/category_programming.html" =>
    "http://fr.wikipedia.org/wiki/Cat%C3%A9gorie:Langage_de_programmation",
}

url = urls[target]
raise "target not found" unless url
  
system "wget", url, "-O", target

